version: '3.9'

services:
  database:
    image: postgres:latest
    container_name: postgres-db-talenti
    restart: always
    ports:
      - "${DB_PORT}:${DB_PORT}"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
  api-server:
    build:
      context: ./projects/backend
      dockerfile: Dockerfile
    env_file: .env
    container_name: ${PROJECT_NAME}-${JOB_BASE_NAME}
    image: server/${PROJECT_NAME}
    ports:
      - "${PORT_LOCAL}:${PORT_LOCAL}"
    volumes:
      - ./projects/backend/:/app
      - /app/node_modules
      - /app/src/auths/certs
    depends_on:
      - database